server:
  port: 8081

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        service-name: thrift-xxx-server/rest
        instance-id: ${spring.cloud.consul.discovery.service-name}:${spring.cloud.client.ipAddress}:${server.port}
        prefer-ip-address: true
        tags:
          - 8081
          - http
        register-health-check: true
        health-check-path: /health
        health-check-interval: 10s
        health-check-critical-timeout: 10s

  thrift:
    server:
      service-id: thrift-xxx-server
      port: 26001
